# Generated by Django 4.2.6 on 2023-10-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='laptop/')),
                ('description', models.TextField()),
                ('laptop_types', models.CharField(choices=[('Офисные', 'Офисные'), ('Игровые', 'Игровые'), ('Ультрабуки', 'Ультрабуки')], max_length=100)),
                ('cost', models.PositiveIntegerField()),
                ('release_year', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('Б\\У', 'Б\\У'), ('Новый', 'Новый')], max_length=50)),
            ],
        ),
    ]
