# Generated by Django 4.2.6 on 2023-10-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_laptop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
