# Generated by Django 4.2.6 on 2023-10-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_laptop_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'verbose_name': 'Ноутбук', 'verbose_name_plural': 'Ноутбуки'},
        ),
        migrations.AlterField(
            model_name='laptop',
            name='condition',
            field=models.CharField(choices=[('Б\\У', 'Б\\У'), ('Новый', 'Новый')], max_length=50, null=True, verbose_name='Выберите состояние'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cost',
            field=models.PositiveIntegerField(null=True, verbose_name='Укажите цену'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Добавьте описание'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(null=True, upload_to='laptop/', verbose_name='Загрузите фото'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='laptop_types',
            field=models.CharField(choices=[('Офисные', 'Офисные'), ('Игровые', 'Игровые'), ('Ультрабуки', 'Ультрабуки')], max_length=100, null=True, verbose_name='Выберите тип ноутбука'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.CharField(max_length=100, null=True, verbose_name='Модель ноутбука'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='release_year',
            field=models.PositiveIntegerField(null=True, verbose_name='Укажите год выпуска'),
        ),
    ]
