# Generated by Django 4.2.6 on 2023-10-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_laptop_options_alter_laptop_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Загрузите фото'),
        ),
    ]
